#!/bin/bash

PATTERN=$1
if [ -z "$PATTERN" ];
then
  PATTERN='^\S*'
fi

for item in `openstack server list | grep -v ID | grep -v "+" | grep -E $PATTERN | awk '{ print $2 }'`;
do
  echo $item
  ARRAY=`openstack server show $item | grep addresses | awk '{ print $4 }'`
  NETWORK_NAME=`echo $ARRAY | awk -F '=' '{ print $1 }'`
  VM_VIP=`echo $ARRAY | awk -F '=' '{ print $2 }'`
  NETWORK_ID=`openstack network show $NETWORK_NAME | grep " id " | awk '{ print $4 }'`
  echo $VM_VIP
  echo $NETOWRK_NAME
  echo $NETWORK_ID 

  ip netns exec qdhcp-$NETWORK_ID  ping -c 3 $VM_VIP
  ip netns exec qdhcp-$NETWORK_ID  sshpass -p "cubswin:)" ssh -o StrictHostKeyChecking=no -o ConnectTimeout=5 cirros@$VM_VIP ping -c 3 www.w3-ibm.com
done
