#!/bin/bash
#
# Create multiple VMs on the internal network attached to the default router.
# Change 'NUM_OF_VM' to how ever many VMs you want to create

CIDR=$1
PREFIX=$2
TEST_PREFIX="-IE-"
# Change for stress testing
NUM_OF_VM=3

if [ -z "$CIDR" ];
then
  echo "$0 <cidr> [prefix]"
  exit 0
fi

if [ -z "$PREFIX" ];
then
  TEST_PREFIX="IE-"
fi

VM_NAME=$PREFIX$TEST_PREFIX"vm-1"
SECURITY_GROUP_NAME=$PREFIX$TEST_PREFIX"sec-group-1"
NETWORK_NAME="internal"

if [ `openstack security group list | grep $SECURITY_GROUP_NAME | wc -l` -lt 1 ];
then
  echo "Creating sec group $SECURITY_GROUP_NAME ..."
  openstack security group create $SECURITY_GROUP_NAME --description $SECURITY_GROUP_NAME
  openstack security group rule create --ingress --protocol tcp $SECURITY_GROUP_NAME
  openstack security group rule create --ingress --protocol icmp $SECURITY_GROUP_NAME
fi

# Find network ID
NETWORK_ID=$(openstack network show $NETWORK_NAME | grep -w id | awk '{ print $4 }')

for ((i=0; i<NUM_OF_VM; i++));
do
  if [ `openstack server list | grep $VM_NAME$i | wc -l` -lt 1 ];
  then
    echo "Creating instance $VM_NAME$i ..."
    openstack server create --image cirros --flavor m1.tiny --nic net-id=$NETWORK_ID --security-group $SECURITY_GROUP_NAME $VM_NAME$i
  fi
done
